# Generated by Django 4.0.6 on 2022-07-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_updated_at_alter_user_email_and_more'),
        ('users', '0004_alter_user_phone_number'),
    ]

    operations = [
    ]
